DESCRIPTION = {
    "currency": "currency",
    "appid": "appid",
    "contextid": "contextid",
    "id": "id",
    "classid": "classid",
    "instanceid": "instanceid",
    "amount": "amount",
    "status": "status",
    "original_amount": "original_amount",
    "unowned_id": "unowned_id",
    "unowned_contextid": "unowned_contextid",
    "background_color": "background_color",
    "tradable": "tradable",
    "market_hash_name": "market_hash_name",
    "name_color": "name_color",
    "type": "type",
    "market_name": "market_name",
    "commodity": "commodity",
    "market_tradable_restriction": "market_tradable_restriction",
    "marketable": "marketable",
    "owner": "owner",
}
